# services:
#   - type: web
#     name: tourism-chat-assistant
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: |
#       python tests/test_env.py && \
#       uvicorn app:app --host 0.0.0.0 --port $PORT
#     envVars:
#       - key: HUGGINGFACE_API_KEY
#         sync: false
#       - key: MAKCORPS_API_KEY
#         sync: false
#       - key: TELEGRAM_TOKEN
#         sync: false
#       - key: TWILIO_ACCOUNT_SID
#         sync: false
#       - key: TWILIO_AUTH_TOKEN
#         sync: false
#       - key: FIREBASE_CREDENTIALS
#         sync: false
#     healthCheckPath: /health
#     autoDeploy: true